/**
 * Profiles `legacy_export/` and writes both `docs/profile/data-profile.json` (machine-readable
 * inventories) and `docs/profile/data-profile.md` (the human document).
 *
 * Run with `npm run profile -- --as-of YYYY-MM-DD`. The script is deterministic: it reads the
 * three files, sorts every inventory by count then by value, reads no clock, and takes the
 * reference date for every "future" count from the command line, so two runs with the same
 * argument on the same export produce byte-identical output and the document can be
 * regenerated in review.
 *
 * It decides nothing. Where the data admits two readings (a date ordering, a weight unit,
 * a consent order) both readings are counted and both numbers are printed.
 */
import {mkdirSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {claimRows, notWarnedItems, type ClaimsInput} from './claims.js';
import {EXPORT_DIR, PROFILE_JSON, PROFILE_MD, abs, asOfFromArgv, reproduceCommand} from './cli.js';
import {consentsSections, loadConsents} from './consents.js';
import {crossSections} from './cross.js';
import {delimiterLabel, loadCsv} from './csv.js';
import {intakesSections, loadIntakes} from './intakes.js';
import {loadPatients, patientsSections} from './patients.js';
import {Report, code, plain, renderSection, renderTable, table, type Section} from './report.js';
import {eolLabel, Counter, type FileInfo} from './util.js';

const OUT_MD = abs(PROFILE_MD);
const OUT_JSON = abs(PROFILE_JSON);

function encodingLabel(info: FileInfo): string {
  return `${info.utf8Valid ? 'valid UTF-8' : 'NOT valid UTF-8'}, ${info.nonAsciiBytes} non-ASCII bytes`;
}

function duplicateLineCount(lines: readonly string[]): {groups: number; rows: number} {
  const c = new Counter();
  for (const l of lines) c.add(l);
  const dups = c.entries().filter((e) => e.count > 1);
  return {groups: dups.length, rows: dups.reduce((t, e) => t + e.count, 0)};
}

function main(): void {
  const asOf = asOfFromArgv();
  const patientsCsv = loadCsv(join(EXPORT_DIR, 'patients.csv'));
  const intakesCsv = loadCsv(join(EXPORT_DIR, 'intakes.csv'));
  const patients = loadPatients(patientsCsv);
  const intakes = loadIntakes(intakesCsv);
  const consents = loadConsents(join(EXPORT_DIR, 'consents.jsonl'));

  const report = new Report();
  const sections: Section[] = [
    ...patientsSections(patients, {asOf}),
    ...intakesSections(intakes, {asOf, patients, consentPatientIds: consents.patientIds}),
    ...consentsSections(consents, {asOf, patientLegacyIds: new Set(patients.legacyId)}),
    ...crossSections({patients, intakes, consents, asOf}),
  ];
  for (const s of sections) report.add(s);

  const claimsInput: ClaimsInput = {sections, patients, intakes, consents, asOf};
  const claims = claimRows(claimsInput);
  const notWarned = notWarnedItems(claimsInput);

  // ---- markdown -----------------------------------------------------------------
  const files: Array<{info: FileInfo; delimiter: string; header: readonly string[]; dataRows: number}> = [
    {info: patientsCsv.info, delimiter: delimiterLabel(patientsCsv.delimiter), header: patientsCsv.header, dataRows: patientsCsv.rows.length},
    {info: intakesCsv.info, delimiter: delimiterLabel(intakesCsv.delimiter), header: intakesCsv.header, dataRows: intakesCsv.rows.length},
    {info: consents.info, delimiter: 'not applicable (JSON Lines)', header: ['patient_legacy_id', 'type', 'action', 'at', 'version'], dataRows: consents.events.length},
  ];

  const md: string[] = [
    '# Legacy export data profile',
    '',
    `What \`legacy_export/\` actually contains, column by column. Generated by \`${reproduceCommand('profile', asOf)}\`,`,
    `which writes this file and \`${PROFILE_JSON}\` from the export in one pass; every number below comes from that run.`,
    `**Reference date: ${asOf}** (the \`--as-of\` argument). Every "future" count in this document means "after ${asOf}";`,
    'nothing is read from the clock or inferred from the data.',
    '',
    'This document describes and counts. It does not label anything wrong and proposes no mapping, normalisation',
    'or merge rule: those are ADR decisions (CLAUDE.md §1) and they need this inventory first.',
    '',
    '## Files as read from disk',
    '',
  ];
  md.push(
    ...renderTable(
      table(
        '',
        ['file', 'bytes', 'encoding', 'BOM', 'line endings', 'delimiter', 'header fields', 'data rows', 'blank lines', 'duplicate full rows'],
        files.map((f) => {
          const dup = duplicateLineCount(f.info.name.endsWith('.jsonl') ? f.info.lines : f.info.lines.slice(1));
          return [
            code(f.info.name),
            String(f.info.bytes),
            encodingLabel(f.info),
            f.info.hasBom ? 'yes' : 'no',
            eolLabel(f.info),
            plain(f.delimiter),
            String(f.header.length),
            String(f.dataRows),
            String(f.info.blankLines),
            `${dup.groups} groups / ${dup.rows} rows`,
          ];
        }),
      ),
    ),
  );
  md.push(
    ...renderTable(
      table(
        'Header as exported',
        ['file', 'columns in order'],
        files.map((f) => [code(f.info.name), f.header.map((h) => code(h)).join(', ')]),
      ),
    ),
  );
  md.push(
    'Conventions used throughout:',
    '',
    '- **raw value**: the field exactly as exported, shown inside backticks so leading and trailing whitespace is',
    '  visible. `|` is escaped as `\\|` and tabs, carriage returns and newlines as `\\t`, `\\r`, `\\n`.',
    '- **folded**: trim, lowercase, then collapse internal whitespace runs to one space.',
    '- **shape**: every digit replaced by `9`, every lowercase letter by `a`, every uppercase letter by `A`,',
    '  punctuation and whitespace kept verbatim. A **collapsed shape** additionally collapses a run of one',
    '  shape character to `X+` (`aaa.aa` becomes `a+.a+`).',
    '- A column with 60 or fewer distinct raw values gets its complete value table; the others get a shape',
    '  inventory. Where even the shape inventory is past 60 rows the document falls back to the collapsed shape',
    `  or to a length and character-class inventory, and \`docs/profile/data-profile.json\` carries the complete exact-shape`,
    '  inventory for every such column.',
    '- Every row of every file lands in exactly one row of its column inventory; empty values are their own',
    '  inventory row.',
    `- **future**: a date after ${asOf}, the reference date given with \`--as-of\`. Where a value has several`,
    '  plausible readings, "under some ordering" counts it when any reading is future and "under every ordering"',
    '  only when all are.',
    '- **date ordering classes**, used in every date shape table: `day-first` means one of the two non-year',
    '  parts is greater than 12 and must therefore be the day; `month-first` means the second of the pair must',
    '  be the day; `ambiguous` means both parts are 12 or less, so the value is a valid date under either',
    '  ordering; `invalid` means no ordering yields a calendar date. For a year-first shape the pair is the two',
    '  trailing parts, so `day-first` there reads as YYYY-DD-MM.',
    '',
    '## Inventories',
    '',
  );
  for (const s of sections.filter((x) => x.group === 'inventory')) md.push(...renderSection(report, s, '###'));

  md.push('## Cross-file', '');
  for (const s of sections.filter((x) => x.group === 'cross')) md.push(...renderSection(report, s, '###'));

  md.push('## Verification of EXPORT-NOTES.md claims', '');
  md.push(
    'Every claim in EXPORT-NOTES.md, in the order the notes make them: first the column-reference tables, then',
    'the known caveats. `unverifiable` means the claim is about intent or history that this export cannot show.',
    '',
  );
  md.push(
    ...renderTable(
      table(
        '',
        ['claim', 'verdict', 'evidence', 'what the numbers say'],
        claims.map((c) => [plain(c.claim), c.verdict, report.pnList(c.evidence), plain(c.note)]),
      ),
    ),
  );

  md.push('## Not warned about in EXPORT-NOTES.md', '');
  md.push('Findings the notes do not mention at all. Each is a count, not a judgement.', '');
  for (const item of notWarned) md.push(`- ${plain(item.text)} (${report.pnList(item.evidence)})`);
  md.push('');

  mkdirSync(dirname(OUT_MD), {recursive: true});
  writeFileSync(OUT_MD, md.join('\n'), 'utf8');

  // ---- json ---------------------------------------------------------------------
  const columns: Record<string, unknown> = {};
  for (const s of sections) if (s.group === 'inventory' && s.key.includes('.')) columns[s.key] = s.json;
  const json = {
    generatedBy: reproduceCommand('profile', asOf),
    reproduce: reproduceCommand('profile', asOf),
    asOf,
    files: files.map((f) => ({
      name: f.info.name,
      bytes: f.info.bytes,
      bom: f.info.hasBom,
      utf8Valid: f.info.utf8Valid,
      nonAsciiBytes: f.info.nonAsciiBytes,
      lineEndings: {crlf: f.info.crlf, bareLf: f.info.loneLf, bareCr: f.info.loneCr},
      endsWithNewline: f.info.endsWithNewline,
      physicalLines: f.info.physicalLines,
      blankLines: f.info.blankLines,
      delimiter: f.delimiter,
      header: f.header,
      dataRows: f.dataRows,
      duplicateFullRows: duplicateLineCount(f.info.name.endsWith('.jsonl') ? f.info.lines : f.info.lines.slice(1)),
    })),
    columns,
    crossFile: Object.fromEntries(sections.filter((s) => s.group === 'cross').map((s) => [s.key, s.json])),
    // Index only: the inventories themselves live once, under `columns` and `crossFile`.
    sections: sections.map((s) => ({
      pn: report.pn(s.key),
      key: s.key,
      title: s.title,
      group: s.group,
    })),
    exportNotesClaims: claims.map((c) => ({
      claim: c.claim,
      verdict: c.verdict,
      evidence: c.evidence.map((k) => report.pn(k)),
      evidenceKeys: c.evidence,
      note: c.note,
    })),
    notWarnedAbout: notWarned.map((i) => ({
      finding: i.text,
      evidence: i.evidence.map((k) => report.pn(k)),
      evidenceKeys: i.evidence,
    })),
  };
  writeFileSync(OUT_JSON, `${JSON.stringify(json, null, 2)}\n`, 'utf8');

  process.stdout.write(
    `wrote ${PROFILE_MD} (${md.length} lines) and ${PROFILE_JSON}, as of ${asOf}\n` +
      `sections: ${sections.length}, claims: ${claims.length}, not-warned findings: ${notWarned.length}\n`,
  );
}

main();
